//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodbyeFields_GAMC_Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoodbyeFields_GAMC_Utility.UtilityResource", typeof(UtilityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:44359/ReturnURL?guid=.
        /// </summary>
        public static string BaseURL {
            get {
                return ResourceManager.GetString("BaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBalance Service called to check balance with request parameter, PlayerId .
        /// </summary>
        public static string CheckBalanceMessage {
            get {
                return ResourceManager.GetString("CheckBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckPlayerExistence.
        /// </summary>
        public static string CheckPlayerExistence {
            get {
                return ResourceManager.GetString("CheckPlayerExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_CheckPlayerExistence.
        /// </summary>
        public static string CheckPlayerExistenceSP {
            get {
                return ResourceManager.GetString("CheckPlayerExistenceSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckTransactionStatus.
        /// </summary>
        public static string CheckTransactionStatus {
            get {
                return ResourceManager.GetString("CheckTransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_VoidTransactionStatus.
        /// </summary>
        public static string CheckTransactionStatusSP {
            get {
                return ResourceManager.GetString("CheckTransactionStatusSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionFromDate can not be greater then TransactionToDate .
        /// </summary>
        public static string DateErrorMessage {
            get {
                return ResourceManager.GetString("DateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_WalletDeposit.
        /// </summary>
        public static string DepositSP {
            get {
                return ResourceManager.GetString("DepositSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in {MethodName} method, Error : {ErrorMessage} .
        /// </summary>
        public static string ErrorInMethod {
            get {
                return ResourceManager.GetString("ErrorInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} method executed successfully. .
        /// </summary>
        public static string ExecutedSuccessfully {
            get {
                return ResourceManager.GetString("ExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutePayment.
        /// </summary>
        public static string ExecutePayment {
            get {
                return ResourceManager.GetString("ExecutePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateJwtToken.
        /// </summary>
        public static string GenerateJwtToken {
            get {
                return ResourceManager.GetString("GenerateJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBalance.
        /// </summary>
        public static string GetBalance {
            get {
                return ResourceManager.GetString("GetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance of a player .
        /// </summary>
        public static string GetBalanceMessage {
            get {
                return ResourceManager.GetString("GetBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetBalance.
        /// </summary>
        public static string GetBalanceSP {
            get {
                return ResourceManager.GetString("GetBalanceSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44359/Home/SuccesReturn?ID=.
        /// </summary>
        public static string HomeControllerReturnURL {
            get {
                return ResourceManager.GetString("HomeControllerReturnURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dbprod/GoodbyeFields-API/PaymentWithPaypal.
        /// </summary>
        public static string HomePayPalAction {
            get {
                return ResourceManager.GetString("HomePayPalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Balance in wallet .
        /// </summary>
        public static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} service starts with request parameters : {RequestParameter} .
        /// </summary>
        public static string LogServiceStartMessage {
            get {
                return ResourceManager.GetString("LogServiceStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} method starts with request parameters : {RequestParameter} .
        /// </summary>
        public static string LogStartMessage {
            get {
                return ResourceManager.GetString("LogStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dbprod/GoodbyeFields-API/ReturnURL?guid=.
        /// </summary>
        public static string PayPalBaseURL {
            get {
                return ResourceManager.GetString("PayPalBaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dbprod/GoodbyeFields-GAMC/Home/Cancel.
        /// </summary>
        public static string PayPalCancel {
            get {
                return ResourceManager.GetString("PayPalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dbprod/GoodbyeFields-GAMC/Home/Failed?Failure_reason=.
        /// </summary>
        public static string PayPalFailed {
            get {
                return ResourceManager.GetString("PayPalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dbprod/GoodbyeFields-GAMC/Home/SuccesReturn?ID=.
        /// </summary>
        public static string PayPalSuccess {
            get {
                return ResourceManager.GetString("PayPalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in PlayerId parameter .
        /// </summary>
        public static string PlayerIdError {
            get {
                return ResourceManager.GetString("PlayerIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetPlayerList.
        /// </summary>
        public static string PlayerList {
            get {
                return ResourceManager.GetString("PlayerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player does not exist..
        /// </summary>
        public static string PlayerNotExist {
            get {
                return ResourceManager.GetString("PlayerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnToCancel.
        /// </summary>
        public static string ReturnToCancel {
            get {
                return ResourceManager.GetString("ReturnToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnURL.
        /// </summary>
        public static string ReturnURL {
            get {
                return ResourceManager.GetString("ReturnURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnURLstart.
        /// </summary>
        public static string ReturnURLstart {
            get {
                return ResourceManager.GetString("ReturnURLstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavePaypalResonse.
        /// </summary>
        public static string SavePaypalResonseService {
            get {
                return ResourceManager.GetString("SavePaypalResonseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SavePaypalResponse.
        /// </summary>
        public static string SavePaypalResonseSP {
            get {
                return ResourceManager.GetString("SavePaypalResonseSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavePayPalResponse.
        /// </summary>
        public static string SavePayPalResponse {
            get {
                return ResourceManager.GetString("SavePayPalResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MethodName} Service executed successfully. .
        /// </summary>
        public static string ServiceExecutedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure {SPName} end .
        /// </summary>
        public static string SPExecutionEnd {
            get {
                return ResourceManager.GetString("SPExecutionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure {SPName} start .
        /// </summary>
        public static string SPExecutionStart {
            get {
                return ResourceManager.GetString("SPExecutionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Already Void.
        /// </summary>
        public static string TransactionAlreadyVoid {
            get {
                return ResourceManager.GetString("TransactionAlreadyVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in TransactionAmount parameter .
        /// </summary>
        public static string TransactionAmountError {
            get {
                return ResourceManager.GetString("TransactionAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in TransactionCode parameter .
        /// </summary>
        public static string TransactionCodeError {
            get {
                return ResourceManager.GetString("TransactionCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in TransactionFromDate parameter .
        /// </summary>
        public static string TransactionFromDateError {
            get {
                return ResourceManager.GetString("TransactionFromDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionHistory.
        /// </summary>
        public static string TransactionHistory {
            get {
                return ResourceManager.GetString("TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GetPlayerTransactionHistory.
        /// </summary>
        public static string TransactionHistorySP {
            get {
                return ResourceManager.GetString("TransactionHistorySP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in TransactionId parameter .
        /// </summary>
        public static string TransactionIdError {
            get {
                return ResourceManager.GetString("TransactionIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Completed Successfully. .
        /// </summary>
        public static string TransactionMessage {
            get {
                return ResourceManager.GetString("TransactionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Not Found.
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in TransactionToDate parameter .
        /// </summary>
        public static string TransactionToDateError {
            get {
                return ResourceManager.GetString("TransactionToDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction history of a player .
        /// </summary>
        public static string TrasactionHistoryMessage {
            get {
                return ResourceManager.GetString("TrasactionHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoidTransaction.
        /// </summary>
        public static string VoidTransaction {
            get {
                return ResourceManager.GetString("VoidTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction void successfully .
        /// </summary>
        public static string VoidTransactionMessage {
            get {
                return ResourceManager.GetString("VoidTransactionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_VoidATransaction.
        /// </summary>
        public static string VoidTransactionSP {
            get {
                return ResourceManager.GetString("VoidTransactionSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        public static string Withdrawal {
            get {
                return ResourceManager.GetString("Withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_WalletWithdrawal.
        /// </summary>
        public static string WithdrawalSP {
            get {
                return ResourceManager.GetString("WithdrawalSP", resourceCulture);
            }
        }
    }
}
